
FROM jrottenberg/ffmpeg:5.1-nvidia2004
# 5.1.4-nvidia2004

RUN mkdir -p /app
WORKDIR /app
RUN git clone https://github.com/vncntprvst/whisk.git
RUN pip install .
RUN python update_permissions.py

# WIP ...

# FROM wanglabneuro/whisk-ww:latest

# # Update the Whisk package 
# WORKDIR /app/whisk
# RUN git pull origin master
# RUN pip install .
# RUN python update_permissions.py

# # Update the WhiskiWrap package 
# WORKDIR /app/WhiskiWrap/
# RUN git pull origin master
# RUN pip install .

# WORKDIR /data

