# Use FFmpeg image 
FROM jrottenberg/ffmpeg:5.1.4-nvidia2204
# ffmpeg configured with '--enable-nvenc' flag 

LABEL maintainer="Vincent Prevosto <prevosto@mit.edu>"

ENV DEBIAN_FRONTEND noninteractive

# # Matlab is needed to build the whisk mex files
COPY --from=wanglabneuro/matlab_om:2021b /usr/local/MATLAB/R2021b /usr/local/MATLAB/R2021b
ENV PATH="/usr/local/MATLAB/R2021b/bin:${PATH}"

# Package installs
# Fix fontconfig issue and install Qt5 dependencies
RUN apt-get update && \
    apt-get install -y libfontconfig1 libfreetype6 fontconfig-config

RUN apt-get download fontconfig && \
    dpkg -i fontconfig*.deb && \
    rm -rf /var/cache/fontconfig/* && \
    fc-cache -rv && \
    apt-get install -y qtbase5-dev libqt5svg5-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# RUN apt-get install -y --reinstall fontconfig 
# RUN dpkg --configure fontconfig

# Install the rest of the packages (install Qt5 dependencies)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    zlib1g-dev \
    libbz2-dev \
    libvorbis-dev \
    libxcb-xinerama0 \
    pkg-config \
    bison \
    gawk \
    git-core \
    nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install whisk
RUN mkdir -p /app
WORKDIR /app
RUN git clone https://github.com/vncntprvst/whisk.git

# Install whisk
# Run cmake configure & build process
WORKDIR /app/whisk
RUN mkdir build
WORKDIR /app/whisk/build
RUN cmake ..
RUN make

# add whisk binaries to path
ENV PATH="$PATH:/app/whisk/build"

# delete Matlab 
RUN rm -rf /usr/local/MATLAB

WORKDIR /data

ENTRYPOINT []