FROM jrottenberg/ffmpeg:5.1-nvidia2004
# ffmpeg configured with '--enable-nvenc' flag 

LABEL maintainer="Vincent Prevosto <prevosto@mit.edu>"

ENV DEBIAN_FRONTEND noninteractive

# Package installs
RUN apt update && \
    apt install -y --no-install-recommends \
    build-essential \
    cmake \
    zlib1g-dev \
    libbz2-dev \
    libvorbis-dev \
    pkg-config \
    bison \
    gawk \
    git-core \
    nano && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
    
RUN mkdir -p /app
WORKDIR /app
# Clone Mitch Clough's whisk fork of the original repo https://github.com/nclack/whisk.git 
RUN git clone https://github.com/mitchclough/whisk.git 

# Install whisk
# Run cmake configure & build process
WORKDIR /app/whisk
RUN mkdir build
WORKDIR /app/whisk/build
RUN cmake ..
RUN make

# add whisk binaries to path
ENV PATH="$PATH:/app/whisk/build"

WORKDIR /data

ENTRYPOINT []